import type { LevelSixSubmission } from "@htlm/protocol";

export type LevelSixChallenge =
  | { id: string; station: 1 | 4; type: "singleChoice"; prompt: string; options: Array<{ id: string; text: string }>; solution: LevelSixSubmission & { type: "singleChoice" }; explanation: string; points: 25; demo: true }
  | { id: string; station: 2; type: "classification"; prompt: string; options: Array<{ id: string; text: string }>; solution: LevelSixSubmission & { type: "classification" }; explanation: string; points: 25; demo: true }
  | { id: string; station: 3; type: "ordering"; prompt: string; items: Array<{ id: string; text: string }>; solution: LevelSixSubmission & { type: "ordering" }; explanation: string; points: 25; demo: true };

export const LEVEL_SIX_CHALLENGES = [
  { id: "demo-level-06-station-01", station: 1, type: "singleChoice", prompt: "Công nghiệp hóa làm tăng nhu cầu về lao động có kỹ năng, nguyên liệu nông nghiệp, công nghệ và tri thức chuyên môn. Điều này có thể tác động đến quan hệ giữa các lực lượng theo hướng nào?", options: [{ id: "a", text: "Làm vai trò các lực lượng ngày càng giống nhau." }, { id: "b", text: "Tạo thêm những điểm gắn kết về lợi ích giữa các lực lượng." }, { id: "c", text: "Làm giảm nhu cầu phối hợp." }, { id: "d", text: "Chuyển quan hệ thành cạnh tranh thuần túy." }], solution: { type: "singleChoice", optionId: "b" }, explanation: "Quá trình phát triển tạo ra thêm những mối liên hệ và nhu cầu phối hợp giữa các lực lượng.", points: 25, demo: true },
  { id: "demo-level-06-station-02", station: 2, type: "classification", prompt: "Một chính sách hướng đến người lao động, người sản xuất và những nhóm còn gặp khó khăn trong tiếp cận cơ hội phát triển.\nÝ nghĩa nổi bật của chính sách này đối với việc củng cố liên minh là gì?", options: [{ id: "a", text: "Làm mọi nhóm có điều kiện kinh tế tương đương." }, { id: "b", text: "Hạn chế sự xuất hiện của các tầng lớp mới." }, { id: "c", text: "Giảm khác biệt giữa các nghề nghiệp." }, { id: "d", text: "Góp phần xử lý các vấn đề xã hội và tạo sự đồng thuận rộng hơn." }], solution: { type: "classification", optionId: "d" }, explanation: "Việc xử lý các vấn đề xã hội và mở rộng cơ hội phát triển góp phần tạo điều kiện cho sự đồng thuận giữa các lực lượng.", points: 25, demo: true },
  { id: "demo-level-06-station-03", station: 3, type: "ordering", prompt: "Sắp xếp các ý thành một tiến trình thể hiện cách củng cố quan hệ liên minh trong điều kiện xã hội có nhiều lợi ích khác nhau.", items: [{ id: "d", text: "Tạo điều kiện củng cố sự phối hợp và đồng thuận" }, { id: "a", text: "Nhận diện sự đa dạng về vị trí và lợi ích" }, { id: "b", text: "Xác định những mục tiêu và lợi ích chung" }, { id: "c", text: "Điều hòa những khác biệt lợi ích có thể điều chỉnh" }], solution: { type: "ordering", order: ["a", "b", "c", "d"] }, explanation: "Đây là cách chuyển thể cho gameplay từ các ý trong bộ câu hỏi về lợi ích riêng, mục tiêu chung, điều hòa lợi ích và củng cố phối hợp; không phải câu nguyên văn của bộ 30.", points: 25, demo: true },
  { id: "demo-level-06-station-04", station: 4, type: "singleChoice", prompt: "Trong một xã hội có nhiều nhóm với vị trí và lợi ích khác nhau, sự đồng thuận nên được hiểu gần nhất là gì?", options: [{ id: "a", text: "Các lực lượng chỉ còn lợi ích chung và không còn lợi ích riêng." }, { id: "b", text: "Các lực lượng có khả năng phối hợp trên những mục tiêu chung dù vẫn tồn tại khác biệt." }, { id: "c", text: "Một lực lượng thống nhất các lực lượng còn lại theo mục tiêu của mình." }, { id: "d", text: "Các lợi ích riêng phải tạm thời bị gác lại." }], solution: { type: "singleChoice", optionId: "b" }, explanation: "Đồng thuận không đồng nghĩa với việc tất cả lực lượng phải có lợi ích giống nhau; trọng tâm là khả năng phối hợp trên những mục tiêu chung.", points: 25, demo: true }
] as const satisfies readonly LevelSixChallenge[];

export const LEVEL_SIX_TIMING = { introMs: 4_500, answerMs: 13_000, revealMs: 3_000 } as const;
